[tool.black]
line-length = 120
target-version = ["py36", "py37"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.idea
  | \build
  | \dist
  | \.vscode
  | \.tox
  | \.pytest_cache
  | \.venv
  | .*\.egg-info
)/
'''
